[package]
name = "automata"
version = "0.1.0"
authors = ["jamie <jamie.y.parkinson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
